add check for PodAntiAffinity not nil
red-hat-storage/ocs-operator pull request #1350
Opened 2021-09-28 05:49 UTC by subhamkrai

add check for PodAntiAffinity not nil before checking
underlying resources otherwise it will cause nil pointer
err. Also updating unit test to test this nil pointer
condition.

Signed-off-by: subhamkrai <srai@redhat.com>

2021-09-28 05:50 UTC, subhamkrai commented
making it draft pr as I'm not able to test in the cluster(struggling with cluster step up)

2021-09-28 05:59 UTC, sp98 requested changes

2021-09-28 05:59 UTC, sp98 commented on controllers/storagecluster/placement.go
>  		if placement.PodAntiAffinity.PreferredDuringSchedulingIgnoredDuringExecution != nil {
```suggestion
		if placement.PodAntiAffinity != nil && placement.PodAntiAffinity.PreferredDuringSchedulingIgnoredDuringExecution != nil {
```

might be easier to read

2021-09-28 06:10 UTC, subhamkrai commented on controllers/storagecluster/placement.go
>  		if placement.PodAntiAffinity.PreferredDuringSchedulingIgnoredDuringExecution != nil {
changed

2021-09-28 06:11 UTC, subhamkrai commented
After taking @agarwal-mudit making it ready for review as this is a small change but I'll also try to test in the local cluster.

2021-09-28 07:27 UTC, agarwal-mudit commented
/ok-to-test

2021-09-28 07:28 UTC, agarwal-mudit commented
/cc @nbalacha @umangachapagain

2021-09-28 15:34 UTC, jarrpa approved these changes
/lgtm

2021-09-28 15:35 UTC, merged

2021-09-28 15:44 UTC, agarwal-mudit commented
/cherry-pick release-4.9

2021-09-29 11:17 UTC, agarwal-mudit commented
/cherry-pick release-4.8

2021-09-29 11:19 UTC, agarwal-mudit commented
@subhamkrai Please create a manual backport PR for release-4.8 as the automated cherry-pick failed because of commits.

2021-09-29 12:10 UTC, subhamkrai commented
> @subhamkrai Please create a manual backport PR for release-4.8 as the automated cherry-pick failed because of commits.

#1354