[WIP]controllers: change resourceManager interface
red-hat-storage/ocs-operator pull request #1450
Opened 2022-01-05 11:14 UTC by iamniting

With the current resourceManager interface there is no way to
communicate the reconcile.Result back to the reconcilePhases as it only
returns the error.

change the interface signature to return the reconcile.Result as well
with the error.

Why?
We do require this change to communicate the Requeue and RequeueAfter to
the reconcilePhases.

Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

2022-01-05 15:03 UTC, oritwas reviewed
Please describe why do we need to return reconcile.Result from ensureCreated.

2022-01-05 15:56 UTC, oritwas approved these changes

2022-01-06 06:53 UTC, sp98 requested changes
nit

2022-01-06 06:53 UTC, sp98 commented on controllers/storagecluster/uninstall_reconciler.go
> +		return reconcile.Result{RequeueAfter: time.Second * time.Duration(1)}, err
would be nice to use this result with 1 second timeout as a constant since its used in a lot of places.

2022-01-07 10:24 UTC, iamniting commented
/hold

2022-01-07 12:51 UTC, iamniting commented
/hold cancel

2022-01-07 13:04 UTC, nbalacha approved these changes

2022-01-07 13:04 UTC, nbalacha commented
/lgtm

2022-01-07 13:55 UTC, merged