Update source-manifests.sh
red-hat-storage/ocs-operator pull request #1472
Opened 2022-02-01 10:32 UTC by b-ranto

This makes the script use oc tool to extract the necessary files -- CSVs
and CRDs from rook and noobaa images. This should be less prone to
errors as it does not try to run the containers. It should also help us
sync with downstream where we can't use podman/docker to run the
containers.

Signed-off-by: Boris Ranto <branto@redhat.com>

2022-02-01 12:20 UTC, b-ranto commented
FYI: This worked sa expected DS.

2022-02-01 12:38 UTC, umangachapagain commented
CI is failing for 2 things:
`ocs-operator-ci` is failing shellcheck. Run it locally to fix the script.
`verify-latest-csv` failed because `oc` tool is not available inside the container that generates CSV. We'll have to install it.

2022-02-01 13:30 UTC, b-ranto commented
@umangachapagain I fixed the `ocs-operator-ci` shellcheck failures. I'm not sure what to do about the `oc` tool missing. Can you point me to a file that I should patch/fix?

2022-03-29 07:24 UTC, umangachapagain commented
/retest

2022-04-04 14:55 UTC, jarrpa requested changes
Oh.... I didn't know about the image extract command! This is exciting!

2022-04-04 14:55 UTC, jarrpa commented on Makefile
> +export OCS_OC_PATH=$(shell which oc)
Setting it this way now overrides the intended behavior of allowing the user to specify their own custom `oc` path (which I use regularly :wink: ). See here: https://github.com/red-hat-storage/ocs-operator/blob/main/hack/common.sh#L39

Similarly, if you don't explicit `export` the variable then it won't be available in any of the subshells called by `make`. In general I would rather see this in the `common.sh` file.

2022-04-04 14:55 UTC, jarrpa commented on Makefile
> +	export latest_oc_client_version=$$(curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/ 2>/dev/null | grep -o \"openshift-client-linux-4.*tar.gz\" | tr -d \") ;\
Is this really the best way to determine the latest version? Shouldn't we be using https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/release.txt instead?

Even so, we don't always want to be using the latest OCP binaries. While this is fine for `main`, we probably want to restrict ourselves to the target version of our current release.

2022-04-04 14:55 UTC, jarrpa commented on hack/source-manifests.sh
> +	${OCS_OC_PATH} image extract --confirm "${NOOBAA_IMAGE}" --path /usr/local/bin/noobaa-operator:./
Use `mktemp` for this as you did for Rook-Ceph.

2022-10-14 07:27 UTC, malayparida2000 commented
@b-ranto Is this PR still required?

2025-08-11 06:30 UTC, closed without merging