expose option to force remove the OSD in osd removal template
red-hat-storage/ocs-operator pull request #1501
Opened 2022-02-08 15:04 UTC by subhamkrai

adding option to expose `--force-osd-removal` `<true/false>`.
It will help when Ceph indicates the OSD is not safe-to-destroy.

Signed-off-by: subhamkrai <srai@redhat.com>

2022-02-08 18:41 UTC, travisn requested changes

2022-02-08 18:41 UTC, travisn commented on controllers/storagecluster/job_templates.go
> +				DisplayName: "FORCE_OSD_REMOVAL",
```suggestion
				DisplayName: "Force OSD Removal",
```

2022-02-08 18:41 UTC, travisn commented on controllers/storagecluster/job_templates.go
> +				Required:    false,
I believe we also need to specify the default value as:
```
Value: "false",
```
Without that I assume the default is just empty, which will likely cause an error in Rook. But we need to test these template changes in an openshift cluster to confirm the default behavior.

2022-02-08 18:41 UTC, travisn commented on controllers/storagecluster/job_templates.go
> +The parameter FORCE_OSD_REMOVAL require bool value.`,
```suggestion
A flag indicating whether the OSD should be forcefully removed. Valid values are true or false. The default value is false. If an OSD is being removed that could lead to data loss, the OSD will not be removed by default. If you see the osd removal fails and you are sure the OSD should be removed, set this flag to true and run the job again.
```

2022-02-09 03:37 UTC, agarwal-mudit commented
/cherry-pick release-4.10

2022-02-11 02:38 UTC, subhamkrai commented
> The changes look good. Can you comment on the testing you've been able to run? From an offline conversation I think it's good to go, but would be good to summarize it here.

So, when running the template without flag `force-osd-removal`, I was able to verify the default value was `false`. And when I ran the template with the flag, in the logs I was able to see `force-osd-removal=true` but osd was not purged because it was healthy(which is expected).

2022-02-14 17:58 UTC, travisn commented
/lgtm
@agarwal-mudit @jarrpa Can we get an approve on this?

2022-02-15 03:51 UTC, agarwal-mudit commented
/retest

2022-02-15 04:16 UTC, agarwal-mudit commented
/approve

2022-02-15 05:14 UTC, merged

2022-08-23 03:53 UTC, subhamkrai commented
/cherry-pick release-4.9

2022-08-23 03:55 UTC, subhamkrai commented
/cherry-pick release-4.8

2022-08-23 03:57 UTC, subhamkrai commented
> @subhamkrai: #1501 failed to apply on top of branch "release-4.8":
> 
> ```
> Applying: expose option to force remove the OSD in osd removal template
> Using index info to reconstruct a base tree...
> A	controllers/storagecluster/job_templates.go
> A	controllers/storagecluster/job_templates_test.go
> Falling back to patching base and 3-way merge...
> CONFLICT (modify/delete): controllers/storagecluster/job_templates_test.go deleted in HEAD and modified in expose option to force remove the OSD in osd removal template. Version expose option to force remove the OSD in osd removal template of controllers/storagecluster/job_templates_test.go left in tree.
> CONFLICT (modify/delete): controllers/storagecluster/job_templates.go deleted in HEAD and modified in expose option to force remove the OSD in osd removal template. Version expose option to force remove the OSD in osd removal template of controllers/storagecluster/job_templates.go left in tree.
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 expose option to force remove the OSD in osd removal template
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

I'll create manual BP for 4.8, 4.7, 4.6