update imagefeature in rbd storageclass
red-hat-storage/ocs-operator pull request #1512
Opened 2022-02-11 06:49 UTC by Madhu-1

update the image feature from layering to layering,exclusive-lock,object-map,fast-diff as this is required to enable the DR workflow on the rbd images created by this storageclass, and also it provides more crash consistent rbd snapshots.

PS: Minimum kernel version required to map images
created from this storageclass is 8.2+

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>

2022-02-11 06:49 UTC, Madhu-1 commented
/hold

2022-02-11 06:50 UTC, Madhu-1 commented
/assign @jarrpa  @ShyamsundarR @idryomov

2022-02-11 06:51 UTC, Madhu-1 commented
/assign @jarrpa 
/assign @ShyamsundarR 
/assign @idryomov

2022-02-16 15:32 UTC, idryomov requested changes
What about `deep-flatten`?  With the RHEL 7 dependency gone, is there a reason to not enable it by default?

2022-02-16 15:38 UTC, Madhu-1 commented
> What about `deep-flatten`? With the RHEL 7 dependency gone, is there a reason to not enable it by default?

@idryomov Thanks for the review. These are the image features we added for the DR use case. what advantages we will get if we enable deep flatten on the rbd images we create for the PVC both for DR and Non-DR workflow? will there be any problems if we enable deep-flatten by default in anycases?

2022-02-16 15:57 UTC, Madhu-1 commented
> > What about `deep-flatten`? With the RHEL 7 dependency gone, is there a reason to not enable it by default?
> 
> @idryomov Thanks for the review. These are the image features we added for the DR use case. what advantages we will get if we enable deep flatten on the rbd images we create for the PVC both for DR and Non-DR workflow? will there be any problems if we enable deep-flatten by default in anycases?

@idryomov deep flatten is not yet supported in cephcsi https://github.com/ceph/ceph-csi/blob/devel/internal/rbd/rbd_util.go#L193-L212. based on the input I will send PR to consider deep-flatten in cephcsi

2022-02-16 20:02 UTC, idryomov commented
> will there be any problems if we enable deep-flatten by default in anycases (for snapshots/clones etc)?

No, it's been enabled by default in Ceph for years.

2022-02-16 20:06 UTC, idryomov commented
While we are at it, is there a reason we are spelling out image features at all?  `layering,exclusive-lock,object-map,fast-diff,deep-flatten` is actually what librbd has defaulted to for a long time now.  Now that we aren't constrained by an old kernel, let's consider leaving it up for librbd and/or Ceph CSI users and not define any features in the default storage class.

2022-02-17 07:05 UTC, Madhu-1 commented
> While we are at it, is there a reason we are spelling out image features at all? `layering,exclusive-lock,object-map,fast-diff,deep-flatten` is actually what librbd has defaulted to for a long time now. Now that we aren't constrained by an old kernel, let's consider leaving it up for librbd and/or Ceph CSI users and not define any features in the default storage class.

@idryomov I sent PR to add this support https://github.com/ceph/ceph-csi/pull/2885. as we need to support older kernel versions in upstream cephcsi, I kept the backward compatibility and if the image feature is not present in storageclass then we will use the defaults.

Thinking about one corner case, if some other new image features become the default in librbd and we still need to support older kernel version (8.2+) in ODF will it be problematic?

As we are adding deep-flatten by default will it also increase the storage consumption on the ceph cluster if we create clones and snapshots? I still need to test this one.

@ShyamsundarR any thoughts?

2022-02-22 16:01 UTC, Madhu-1 commented
Had a discussion with @idryomov @ShyamsundarR about adding deep-flatten by default, as there are no known problems with adding it as default parameter, adding to storageclass now. PTAL

2022-03-29 06:36 UTC, umangachapagain commented
@Madhu-1 If this can be merged now, can you rebase and remove hold?

2022-03-29 06:38 UTC, Madhu-1 commented
Still not decided yet, waiting for the QE results to merge this one. cc @agarwal-mudit

2022-04-06 07:07 UTC, Madhu-1 commented
/hold cancel

2022-04-06 07:07 UTC, Madhu-1 commented
/cancel hold

2022-04-06 07:08 UTC, Madhu-1 commented
@agarwal-mudit PR is rebased and updated PTAL

2022-04-06 08:06 UTC, agarwal-mudit approved these changes
/lgtm

2022-04-06 09:46 UTC, Madhu-1 commented
/retest-required

2022-04-06 13:26 UTC, Madhu-1 commented
/test ocs-operator-bundle-e2e-aws

2022-04-06 13:54 UTC, Madhu-1 commented
```
I0406 10:51:20.452964       1 utils.go:191] ID: 55 Req-ID: pvc-f52e19fb-9001-4a3a-8011-adcbe990ea4e GRPC call: /csi.v1.Controller/CreateVolume
I0406 10:51:20.453078       1 utils.go:195] ID: 55 Req-ID: pvc-f52e19fb-9001-4a3a-8011-adcbe990ea4e GRPC request: {"capacity_range":{"required_bytes":53687091200},"name":"pvc-f52e19fb-9001-4a3a-8011-adcbe990ea4e","parameters":{"clusterID":"openshift-storage","csi.storage.k8s.io/pv/name":"pvc-f52e19fb-9001-4a3a-8011-adcbe990ea4e","csi.storage.k8s.io/pvc/name":"db-noobaa-db-pg-0","csi.storage.k8s.io/pvc/namespace":"openshift-storage","imageFeatures":"layering,deep-flatten,exclusive-lock,object-map,fast-diff","imageFormat":"2","pool":"test-storagecluster-cephblockpool"},"secrets":"***stripped***","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
E0406 10:51:20.453203       1 rbd_util.go:1291] ID: 55 Req-ID: pvc-f52e19fb-9001-4a3a-8011-adcbe990ea4e failed to validate image features invalid feature deep-flatten
E0406 10:51:20.453227       1 utils.go:200] ID: 55 Req-ID: pvc-f52e19fb-9001-4a3a-8011-adcbe990ea4e GRPC error: rpc error: code = InvalidArgument desc = invalid feature deep-flatten
```
ci/prow/ocs-operator-bundle-e2e-aws test is failing for the above reason, we need to  update the Rook version to 1.9 to pull the latest cephcsi changes

2022-04-06 13:54 UTC, Madhu-1 commented
CI logs https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/red-hat-storage_ocs-operator/1512/pull-ci-red-hat-storage-ocs-operator-main-ocs-operator-bundle-e2e-aws/1511641589942849536/artifacts/ocs-operator-bundle-e2e-aws/gather-extra/artifacts/pods/openshift-storage_csi-rbdplugin-provisioner-58687fb77c-znb5n_csi-rbdplugin.log

2022-04-14 06:43 UTC, Madhu-1 commented
rebased to pick up Rook 1.9.0-beta. @agarwal-mudit PTAL

2022-04-14 07:08 UTC, humblec commented
> rebased to pick up Rook 1.9.0-beta. @agarwal-mudit PTAL

looks like 1.9 should be available soon too.

2022-04-14 07:19 UTC, Madhu-1 commented
> > rebased to pick up Rook 1.9.0-beta. @agarwal-mudit PTAL
> 
> looks like 1.9 should be available soon too.

it should be fine we don't need to wait for 1.9, we need cephcsi 3.6.0 which is present in 1.9-beta we are good

2022-04-14 08:34 UTC, Madhu-1 commented
> > > rebased to pick up Rook 1.9.0-beta. @agarwal-mudit PTAL
> > 
> > 
> > looks like 1.9 should be available soon too.
> 
> it should be fine we don't need to wait for 1.9, we need cephcsi 3.6.0 which is present in 1.9-beta we are good

We don't have cephcsi 3.6.0 in rook 1.9.beta-0 #1631 should update Rook to 1.9.0 to fix it.

2022-04-14 08:39 UTC, humblec commented
> > > > rebased to pick up Rook 1.9.0-beta. @agarwal-mudit PTAL
> > > 
> > > 
> > > looks like 1.9 should be available soon too.
> > 
> > 
> > it should be fine we don't need to wait for 1.9, we need cephcsi 3.6.0 which is present in 1.9-beta we are good
> 
> We don't have cephcsi 3.6.0 in rook 1.9.beta-0 #1631 should update Rook to 1.9.0 to fix it.

Considering these are downstream repos, good to sync with stable versions.. , main can be an exception though.

2022-04-14 08:39 UTC, humblec commented
> > > > rebased to pick up Rook 1.9.0-beta. @agarwal-mudit PTAL
> > > 
> > > 
> > > looks like 1.9 should be available soon too.
> > 
> > 
> > it should be fine we don't need to wait for 1.9, we need cephcsi 3.6.0 which is present in 1.9-beta we are good
> 
> We don't have cephcsi 3.6.0 in rook 1.9.beta-0 #1631 should update Rook to 1.9.0 to fix it.

Yeah. :+1: ,

2022-04-14 13:34 UTC, agarwal-mudit approved these changes
/lgtm

2022-04-14 13:37 UTC, merged