Update ceph-csi/api and use k8s.gcr.io for csi nfsplugin image
red-hat-storage/ocs-operator pull request #1629
Opened 2022-04-14 06:32 UTC by Rakshith-R

- update ceph-csi api to add nfs sa

This commit updates `github.com/ceph/ceph-csi/api`
so nfs sa is added to `rook-ceph-csi` scc.

Signed-off-by: Rakshith R <rar@redhat.com>

- use k8s.gcr.io for csi nfsplugin image

Use k8s.gcr.io like other kubernetes sidecar
image to pull the nfsplugin image.

Signed-off-by: Rakshith R <rar@redhat.com>

/cc @Madhu-1 @agarwal-mudit @nixpanic @BlaineEXE

2022-04-14 06:41 UTC, Madhu-1 requested changes

2022-04-14 06:41 UTC, Madhu-1 commented on hack/common.sh
> +LATEST_ROOK_CSI_NFS_IMAGE="k8s.gcr.io/sig-storage/nfsplugin:v3.1.0"
you need to run `make gen-latest-csv` as this needs to be updated in ocs-operator.clusterserviceversion.yaml

2022-04-14 07:02 UTC, Madhu-1 approved these changes
LGTM

2022-04-14 07:05 UTC, humblec approved these changes

2022-04-14 07:29 UTC, nixpanic approved these changes

2022-04-18 06:48 UTC, agarwal-mudit approved these changes

2022-04-18 07:57 UTC, merged