Add an annotation to disable components flow in console
red-hat-storage/ocs-operator pull request #1640
Opened 2022-04-25 15:41 UTC by SanjalKatiyar

Added flags are used to disable UI components in Console.
Used to track migration of features from OCP to ODF.
Signed-off-by: SanjalKatiyar <sanjaldhir@gmail.com>

2022-04-26 04:30 UTC, bipuladh requested changes

2022-04-26 04:30 UTC, bipuladh commented on deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
> +    features.ocs.openshift.io/disabled: '["ss-list", "wizard", "add-capacity",
```suggestion
    features.ocs.openshift.io/disabled: '["ss-list", "install-wizard", "add-capacity",
```

2022-04-26 04:30 UTC, bipuladh commented on deploy/bundle/manifests/ocs-operator.clusterserviceversion.yaml
> +      "block-pool", "mcg-store", "object-bucket", "odf-dashboard", "common"]'
```suggestion
      "block-pool", "mcg-resource", "odf-dashboard", "common"]'
```
What is common?

2022-04-26 11:56 UTC, bipuladh commented
/lgtm

2022-04-26 12:16 UTC, umangachapagain commented
/retest

2022-04-26 12:17 UTC, umangachapagain approved these changes

2022-04-26 13:28 UTC, SanjalKatiyar commented
/test verify-latest-csv
/test red-hat-storage-ocs-ci-e2e-aws

2022-04-26 13:35 UTC, SanjalKatiyar commented
/test verify-latest-csv
/test red-hat-storage-ocs-ci-e2e-aws

2022-04-27 04:45 UTC, SanjalKatiyar commented
/retest

2022-04-28 04:44 UTC, bipuladh commented
/lgtm

2022-04-28 05:42 UTC, merged