FF patches
red-hat-storage/ocs-operator pull request #1656
Opened 2022-05-10 08:13 UTC by rexagod

This PR includes fixes for bugs discovered on the consumer side while FF
testing, including:
* Don't filter out PVs based on `spec.storageClassName`, as the index is
  not recognized.
* Move SCC checks under consumer mode.

2022-05-10 09:33 UTC, nb-ohad requested changes

2022-05-10 09:33 UTC, nb-ohad commented on controllers/storageclassclaim/storageclassclaim_controller.go
> +			}
This for-range loop will create an in memory copy of the PV objects, please use index instead:
```suggestion
		for i := range pvList.Items {
			pv := &pvList.Items[i]
			if pv.Spec.StorageClassName == r.storageClassClaim.Name {
				return reconcile.Result{}, fmt.Errorf("StorageClass %s is still in use by one or more PV(s)",
					r.storageClassClaim.Name)
			}
```

2022-05-11 02:23 UTC, rexagod commented
/cc @nb-ohad @Madhu-1 @umangachapagain @iamniting @subhamkrai

2022-05-11 03:44 UTC, Madhu-1 approved these changes

2022-05-11 06:39 UTC, nb-ohad commented
/lgtm

2022-05-11 06:42 UTC, merged

2022-05-11 09:08 UTC, agarwal-mudit commented
/cherrypick release-4.11