removed the whitelisted rbac permissions
red-hat-storage/ocs-operator pull request #1695
Opened 2022-05-24 10:25 UTC by RishabhKodes

2022-05-25 05:38 UTC, umangachapagain requested changes
Please update the commit message according to [this guide](https://github.com/red-hat-storage/ocs-operator/blob/main/CONTRIBUTING.md#commit-and-pull-request-messages).

And, did you mean "wildcard permissions" or "whitelisted permissions"?

2022-05-25 06:13 UTC, RishabhKodes commented
> Please update the commit message according to [this guide](https://github.com/red-hat-storage/ocs-operator/blob/main/CONTRIBUTING.md#commit-and-pull-request-messages).
> 
> And, did you mean "wildcard permissions" or "whitelisted permissions"?

Oops, yeah I mean `whitelisted` permissions.

2022-05-25 12:20 UTC, RishabhKodes commented
/retest

2022-05-31 17:13 UTC, jarrpa commented
/retest

2022-06-08 08:40 UTC, RishabhKodes commented
/retest

2022-06-15 06:24 UTC, RishabhKodes commented
/retest

2022-06-17 20:38 UTC, jarrpa commented
/retest

2022-06-17 20:39 UTC, jarrpa commented
/override ci/prow/red-hat-storage-ocs-ci-e2e-aws

2022-06-18 01:19 UTC, jarrpa commented
/test ocs-operator-ci

2022-06-21 16:38 UTC, nbalacha commented
The rook image needs to be updated in hack/common.sh

2022-06-22 15:06 UTC, jarrpa commented
/override ci/prow/red-hat-storage-ocs-ci-e2e-aws
/override ci/prow/ocs-operator-ci

2022-06-22 15:13 UTC, jarrpa commented
/override ci/prow/red-hat-storage-ocs-ci-e2e-aws, ci/prow/ocs-operator-ci

2022-06-22 15:13 UTC, jarrpa commented
/override ci/prow/red-hat-storage-ocs-ci-e2e-aws
/override ci/prow/ocs-operator-ci

2022-07-27 14:20 UTC, jarrpa commented
/override ci/prow/red-hat-storage-ocs-ci-e2e-aws

2022-07-27 14:20 UTC, jarrpa commented
/test ocs-operator-bundle-e2e-aws

2022-08-09 14:46 UTC, jarrpa requested changes
My apologies for this taking so long, it's been low on my priority list despite my desire to get this merged.

My initial review was relatively superficial, specifically because I was hoping someone else would do the actual analysis. As of yesterday I had another look at it (or rather @nb-ohad's did!) and found that not all wildcards were replaced with equivalent verbs. While I agree we should trim down the total number of verbs that was not the original purpose of the PR, as I understood it. If we're just removing the wildcards, they should be initially replaced with the full list of verbs. AS such, while we've been able to run and validate this PR on our own OCP clusters, the openshift-ci has been continuously failing. Since many other PRs continue to pass and merge, that clearly points to something wrong here, probably one or more missing verbs somewhere.

Since @RishabhKodes has left Red Hat, someone else should either reach out to him or take over the work here. I want to keep his commit as-is, for proper accreditation, so someone should:

1. Add and push another commit to add any and all missing verbs
2. Do more concrete testing to figure out the specific verbs missing and add those.

1 is an absolute requirement for merging this PR. 2 is optional, though also required in the long-term, and can be done either as part of this PR or a follow-up PR.

2025-08-11 06:31 UTC, closed without merging