Enable rbd-mirror daemon restart config automatically
red-hat-storage/ocs-operator pull request #1740
Opened 2022-06-29 07:53 UTC by malayparida2000

Currently, the user has to set this value ceph config set global rbd_mirror_die_after_seconds 3600 via the toolbox,
and that is not a good way for the customer as they don't have toolbox access. So setting this value in the rook-config-override 
configmap.

Note- it will work on fresh clusters not on the upgraded cluster as someone needs to restart rook pods after this configuration is applied

BZ Link-
[https://bugzilla.redhat.com/show_bug.cgi?id=2093266](https://bugzilla.redhat.com/show_bug.cgi?id=2093266)

Signed-off-by: Malay Kumar Parida <mparida@redhat.com>

2022-06-29 07:59 UTC, malayparida2000 commented
/assign @jarrpa 
/assign @agarwal-mudit

2022-06-29 08:06 UTC, agarwal-mudit commented
/cc @ShyamsundarR 
/cc @idryomov

2022-06-29 09:52 UTC, idryomov approved these changes
Ack from the RBD perspective

2022-06-29 13:38 UTC, ShyamsundarR approved these changes

2022-06-29 14:13 UTC, agarwal-mudit commented
/approve
/retest

2022-06-29 14:13 UTC, agarwal-mudit commented
/cherry-pick release-4.10

2022-06-29 14:25 UTC, agarwal-mudit commented
/retest

2022-06-29 14:35 UTC, agarwal-mudit commented
/retest

2022-06-29 14:37 UTC, agarwal-mudit commented
/retest

2022-06-29 14:43 UTC, agarwal-mudit commented
/hold

2022-06-30 06:06 UTC, malayparida2000 commented
/cc @idryomov

2022-06-30 10:31 UTC, idryomov requested changes

2022-06-30 10:31 UTC, idryomov commented on controllers/storagecluster/cephconfig.go
> +mgr/rbd_support/log_level = debug
Did you verify that these settings take effect -- `mgr/rbd_support/log_level` in particular?  In the BZ @travisn said that `defaultRookConfigData` doesn't currently use `ceph config assimilate-conf`, so this is not going to work.

2022-06-30 10:31 UTC, idryomov commented on controllers/storagecluster/cephconfig.go
> +mgr/rbd_support/log_level = debug
The following was suggested instead:

> [...] a setting in the mon store can be applied in Rook inside the postMonStartupActions() method [1] (only in the downstream branch such as 4.11).
> The code would look like: 
>```
> if err := monStore.Set("mgr", "mgr/rbd_support/log_level", "debug"); err != nil {>
>  logger.Errorf("failed to set rbd log level to debug. %v", err)
> }
>```
> [1] https://github.com/red-hat-storage/rook/blob/release-4.11/pkg/operator/ceph/cluster/cluster.go#L489

2022-06-30 15:33 UTC, agarwal-mudit approved these changes
/lgtm

2022-06-30 16:06 UTC, malayparida2000 commented
/retest

2022-06-30 16:07 UTC, agarwal-mudit commented
/hold cancel

We will have separate PR for the debugging related changes

2022-06-30 16:08 UTC, agarwal-mudit commented
/retest

2022-07-01 11:16 UTC, merged