add "noobaa-standalon" daemonplacement for MCG standalone deployment
red-hat-storage/ocs-operator pull request #1827
Opened 2022-09-21 08:49 UTC by utkarsh-pro

This PR adds a "noobaa-standalon" daemonplacement for MCG standalone deployment. This is required so that the user can set tolerations to the MCG pods in standalone mode as well via the storagecluster.

Associated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2115613

Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

2022-09-21 08:51 UTC, utkarsh-pro commented
/cc @jarrpa

2022-09-22 03:48 UTC, malayparida2000 commented
/ok-to-test

2022-09-22 08:53 UTC, iamniting requested changes
Hello @utkarsh-pro changes look good to me, Can you pls correct the typo in the commit-msg?

2022-09-22 08:59 UTC, utkarsh-pro commented
Does it look good now @iamniting?

2022-09-22 09:01 UTC, iamniting commented
> Does it look good now @iamniting?

yes it does

2022-09-22 09:01 UTC, iamniting approved these changes
/lgtm

2022-09-22 12:00 UTC, merged

2022-10-11 12:53 UTC, agarwal-mudit commented
/cherry-pick release-4.11

2022-10-11 13:05 UTC, agarwal-mudit commented
/cherry-pick release-4.10