New containerized & flexible make targets for operator, metrics exporter, must gather, bundle & catalog
red-hat-storage/ocs-operator pull request #1912
Opened 2023-01-08 16:15 UTC by malayparida2000

This is just a start to the series of refactors of the make target, hack scripts & build Dockerfiles.
Currently only new make targets are added & none of the existing things are removed so as to make the refactor easier & safer. 
This PR has-
1. Add variables required for the new make targets in the new .mk file 
2. Add new containerized image build & push make target & Dockerfile 
3. Add new make target to build & push bundle image
4. Add new file based catalog as sqlite based catalog is deprecated

2023-01-09 09:36 UTC, iamniting requested changes

2023-01-10 08:46 UTC, malayparida2000 commented on hack/makefile-vars.mk
> +NOOBAA_BUNDLE_IMG ?= ${NOOBAA_BUNDLE_REGISTRY}/${NOOBAA_BUNDLE_NAME}:${NOOBAA_BUNDLE_TAG}
Done

2023-01-10 08:49 UTC, malayparida2000 commented on Makefile
> +	hack/ensure-opm.sh
Avoided this for now, As it's a binary file & we have to write proper logic to fetch the correct binary for the host OS & Host Arch. The existing hack file has that logic, I will migrate all the tools at once to the makefile format in the future in another refactor.

2023-01-21 15:21 UTC, malayparida2000 commented
closing this PR, Changes will come in multiple broken up PRs in part

2023-01-21 15:21 UTC, closed without merging