feat: support key rotation encryption
red-hat-storage/ocs-operator pull request #1926
Opened 2023-01-31 08:50 UTC by debjyoti-pandit

2023-01-31 08:53 UTC, debjyoti-pandit commented
/assign @umangachapagain 
/assign @vbnrh 
/assign @SanjalKatiyar

2023-01-31 12:08 UTC, umangachapagain requested changes

2023-01-31 12:08 UTC, umangachapagain commented on api/v1/storagecluster_types.go
> +}
We already have `KeyManagementService` just above this. Can't these spec be added there?

2023-02-01 14:16 UTC, Rakshith-R requested changes
/hold

This pr is directly changing noobaa and rook CRDs which it should not.

it needs to wait till related changes are in respective repos. 

cc @SanjalKatiyar

2023-02-02 09:28 UTC, SanjalKatiyar commented on controllers/storagecluster/cephobjectstores.go
> +						Schedule: initData.Spec.Security.KeyManagementService.Schedule,
not needed here... noobaa and ceph are only supported components...

2023-02-15 14:54 UTC, SanjalKatiyar commented on controllers/storagecluster/cephobjectstores.go
> +						EnableKeyRotation: initData.Spec.Security.KeyManagementService.EnableKeyRotation,
no need to make changes to cephobjectstores... that is out of scope of this epic...

2023-02-16 06:27 UTC, SanjalKatiyar commented on controllers/storagecluster/noobaa_system_reconciler.go
> +		nb.Spec.Security.KeyManagementService.Schedule = sc.Spec.Security.KeyManagementService.Schedule
nb.Spec.Security.KeyManagementService.EnableKeyRotation = sc.Spec.Security.KeyManagementService.EnableKeyRotation (if this field is present in the StorageCluster CR)
true (default value, if this field is missing from the CR)

nb.Spec.Security.KeyManagementService.Schedule = 
sc.Spec.Security.KeyManagementService.Schedule (if this field is present in the StorageCluster CR)
'@weekly' (default value, if this field is missing from the CR)

2023-02-16 06:27 UTC, SanjalKatiyar commented on controllers/storagecluster/noobaa_system_reconciler.go
> +		nb.Spec.Security.KeyManagementService.Schedule = sc.Spec.Security.KeyManagementService.Schedule
do the same for ceph as well !

2023-02-16 06:27 UTC, SanjalKatiyar commented on controllers/storagecluster/noobaa_system_reconciler.go
> +		nb.Spec.Security.KeyManagementService.Schedule = sc.Spec.Security.KeyManagementService.Schedule
discussed with @Rakshith-R, will be good to have this for upgrade scenarios (4.12 to 4.13)...

2023-02-16 06:43 UTC, SanjalKatiyar commented on controllers/storagecluster/noobaa_system_reconciler.go
> +		nb.Spec.Security.KeyManagementService.Schedule = sc.Spec.Security.KeyManagementService.Schedule
basically:
ocs opr should pass on any value which is present in CR...
if none present use "true" and  "weekly" by default...

2024-01-29 18:48 UTC, SanjalKatiyar commented
/close

2024-01-29 18:48 UTC, closed without merging