cephcluster: add support for read affinity for RBD volumes
red-hat-storage/ocs-operator pull request #1939
Opened 2023-02-17 05:07 UTC by Rakshith-R

This commit enables read affinity for RBD volumes by setting the "CSI_ENABLE_READ_AFFINITY" environment variable to "true". If it is an external cluster, and the "CSI_ENABLE_READ_AFFINITY" variable is not present in rook-ceph-operator-config ConfigMap, only then it is set to false. This provides flexibility to use the configmap enable and modify this feature for external cluster.

2023-02-17 05:09 UTC, Rakshith-R commented
/cc @iamniting @malayparida2000 @agarwal-mudit

2023-02-17 05:40 UTC, Rakshith-R commented
/wip

I'll modify this pr to use ocsoperatorconfigmap instead.

2023-02-20 05:46 UTC, iamniting requested changes

2023-02-20 05:46 UTC, iamniting commented on controllers/storagecluster/cephcluster.go
> +	err = r.setReadAffinity(sc, !sc.Spec.ExternalStorage.Enable)
why do we need to pass a boolean again when we are already passing the storagecluster? we can read the value from storagecluster directly in the func.

2023-02-20 09:31 UTC, iamniting requested changes
I guess we are missing the CSV changes. We still need to export this to rook envs.

2023-02-20 09:31 UTC, iamniting commented on controllers/storagecluster/cephcluster.go
> +			"CephCluster", klog.KRef(sc.Namespace, sc.Name))
```suggestion
			"StorageCluster", klog.KRef(sc.Namespace, sc.Name))
```

Please change this at other places as well.

2023-02-20 09:58 UTC, malayparida2000 commented
Can we have some the default value false for the key put here https://github.com/red-hat-storage/ocs-operator/blob/main/controllers/ocsinitialization/ocsoperator_config.go#L31. So that rook operator doesn't perceive the variable to be blank  & as it doesn't restart once the storagecluster is created(with the current form the value is not set at the creation of the cm, So once storagecluster reconcile hits your code it will set the value & restart the rook operator pod).

2023-02-20 09:59 UTC, malayparida2000 commented on controllers/ocsinitialization/ocsoperator_config.go
>  		Data: map[string]string{
Let's put a default value here

2023-02-20 10:23 UTC, Rakshith-R commented
hmm, weird requesting review from one user seems to dismiss the request from another user. 
ignore the spam.

CI seems all green now

2023-02-20 10:41 UTC, malayparida2000 approved these changes
/lgtm

2023-02-20 11:52 UTC, iamniting approved these changes

2023-02-20 11:57 UTC, merged