Allow ignoring RBDMirror CR
red-hat-storage/ocs-operator pull request #1968
Opened 2023-03-27 10:00 UTC by umangachapagain

2023-03-27 10:03 UTC, umangachapagain commented
/cherry-pick release-4.13

2023-03-27 10:50 UTC, vbnrh commented on controllers/storagecluster/cephrbdmirrors.go
> +		return reconcile.Result{}, nil
This looks like it only stops ocs from reconciling it ? Don't we need to label it as 'do_not_reconcile' for rook to ignore it as well ?

2023-03-28 05:51 UTC, iamniting requested changes

2023-03-28 05:51 UTC, iamniting commented on api/v1/storagecluster_types.go
> +// ManageCephRBDMirror defines how to reconcile Ceph toolbox
```suggestion
// ManageCephRBDMirror defines how to reconcile CephRBDMirror
```

2023-04-10 13:54 UTC, umangachapagain commented
/cherry-pick release-4.13

2023-04-10 14:02 UTC, iamniting approved these changes

2023-04-10 14:14 UTC, vbnrh requested changes

2023-04-10 14:14 UTC, vbnrh commented on api/v1/storagecluster_types.go
> +	ReconcileStrategy string `json:"reconcileStrategy,omitempty"`
I think it would be safer if you add few enum values for type safety in the CR

2023-04-10 14:17 UTC, vbnrh commented on api/v1/storagecluster_types.go
> +	ReconcileStrategy string `json:"reconcileStrategy,omitempty"`
https://book.kubebuilder.io/reference/markers/crd-validation.html

2023-04-11 06:47 UTC, merged