Fix the OBC alert labels
red-hat-storage/ocs-operator pull request #2023
Opened 2023-04-20 12:53 UTC by aruniiird

ObjectBucketClaim alerts had wrong label format

Wrong format: `{{$labels.objectbucketclaim}}`
Correct format:  `{{ $labels.objectbucketclaim }}`

2023-04-20 17:35 UTC, iamniting commented
@aruniiird Is this required for 4.13? If yes do we have a bug?

2023-04-21 04:57 UTC, aruniiird commented
> @aruniiird Is this required for 4.13? If yes do we have a bug?

Yes @iamniting , BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2188032

2023-04-24 05:53 UTC, umangachapagain requested changes
All the changed alerts are about OBC. Just changing the label to OB is not enough.
Either alert name, message, description everything needs to updated to OB or we need to add objectbucketclaim label.

2023-05-02 08:47 UTC, umangachapagain reviewed
If you just change the first part of expr to `ocs_objectbucketclaim_info * on (namespace, objectbucket) group_left(objectbucketclaim)` it should work i.e. retain the objectbucketclaim label while joining the other half.

2023-09-07 13:31 UTC, aruniiird commented
> All the changed alerts are about OBC. Just changing the label to OB is not enough. Either alert name, message, description everything needs to updated to OB or we need to add objectbucketclaim label.

Yes, you are right. The label, `objectbucketclaim`, is already added. Only the formatting was wrong (if you see other jsonnet files for label template). Corrected it

2023-09-11 09:12 UTC, iamniting approved these changes

2023-09-11 09:12 UTC, iamniting commented
/cherry-pick release-4.14

2023-09-11 09:16 UTC, merged

2023-10-10 08:04 UTC, agarwal-mudit commented
/cherry-pick release-4.13

2023-10-10 08:04 UTC, agarwal-mudit commented
/cherry-pick release-4.12

2023-10-10 08:04 UTC, agarwal-mudit commented
/cherry-pick release-4.11