Use `IfNotPresent` pull policy for images pulled by digest
red-hat-storage/ocs-operator pull request #2056
Opened 2023-05-19 12:09 UTC by jhernand

Currently some of the images use the `Always` image pull policy. That isn't really necessary when the images are pulled by digest instead of by tag, and it introduces an additional network round trip to the image registry server that takes time and may fail. To avoid that this patch changes the `csv-merger` tool so that in addition to merging the CSVs it also changes the `imagePullPolicy` to `IfNotPresent` for images that are pulled by digest.

By default this doesn't produce any change in the merged CSV, because all the images are pulled by tag, but running the following:

```
$ export OCS_IMAGE=quay.io/ocs-dev/ocs-operator@sha256:b22c334a530dc194e758b0e9974376fe75ac1ea5044d079252aeb17081be8e0e
$ make gen-latest-csv
```

Will generate the following diff:

```diff
diff --git a/deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml b/deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
index 91e1f483..4a87e74a 100644
--- a/deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
+++ b/deploy/ocs-operator/manifests/ocs-operator.clusterserviceversion.yaml
@@ -2891,13 +2891,13 @@ spec:
                 - name: NOOBAA_DB_IMAGE
                   value: centos/postgresql-12-centos7
                 - name: PROVIDER_API_SERVER_IMAGE
-                  value: quay.io/ocs-dev/ocs-operator:latest
+                  value: quay.io/ocs-dev/ocs-operator@sha256:b22c334a530dc194e758b0e9974376fe75ac1ea5044d079252aeb17081be8e0e
                 - name: OPERATOR_NAMESPACE
                   valueFrom:
                     fieldRef:
                       fieldPath: metadata.namespace
-                image: quay.io/ocs-dev/ocs-operator:latest
-                imagePullPolicy: Always
+                image: quay.io/ocs-dev/ocs-operator@sha256:b22c334a530dc194e758b0e9974376fe75ac1ea5044d079252aeb17081be8e0e
+                imagePullPolicy: IfNotPresent
                 name: ocs-operator
                 readinessProbe:
                   httpGet:
```

Note how that changed the image pull policy from `Always` to `IfNotPresent`.

Related: https://issues.redhat.com/browse/MGMT-13733

2023-05-22 09:59 UTC, malayparida2000 commented
/ok-to-test

2023-07-18 10:32 UTC, jhernand commented
/test ocs-operator-bundle-e2e-aws

2023-08-04 10:31 UTC, umangachapagain requested changes
We need to commit the generated CSV as well.
Please run `make gen-latest-csv` and add it to the commit.

2023-08-04 11:18 UTC, jhernand commented
> We need to commit the generated CSV as well. Please run `make gen-latest-csv` and add it to the commit.

@umangachapagain the manifest doesn't change when I run `make gen-latest-csv`. That is because by default it uses a tagged image, it will only change when the CSV is regenerated using a digest image. For example:

```shell
$ export OCS_IMAGE=quay.io/ocs-dev/ocs-operator@sha256:b22c334a530dc194e758b0e9974376fe75ac1ea5044d079252aeb17081be8e0e
$ make gen-latest-csv
```

2023-08-04 12:56 UTC, umangachapagain approved these changes

2023-08-07 12:22 UTC, malayparida2000 commented
/test ocs-operator-bundle-e2e-aws

2023-08-07 14:01 UTC, merged

2023-08-17 05:48 UTC, agarwal-mudit commented
/cherry-pick release-4.14