Additions, Fixes & Updations to make ocs-operator-ci
red-hat-storage/ocs-operator pull request #2082
Opened 2023-06-21 12:41 UTC by malayparida2000

2023-06-22 13:33 UTC, iamniting requested changes

2023-06-22 14:06 UTC, malayparida2000 commented on controllers/storagecluster/external_resources_test.go
> +	rand.New(rand.NewSource(time.Now().UnixNano()))
Updated

2023-06-22 14:48 UTC, malayparida2000 commented
/hold

2023-06-22 22:11 UTC, malayparida2000 commented
/unhold

2023-06-23 05:15 UTC, iamniting commented
@malayparida2000 Can you take a look at the failures?

2023-06-28 06:23 UTC, iamniting approved these changes

2023-06-28 06:28 UTC, merged