Bug 2239766: [Release 4.12] fix obc label alerts issue
red-hat-storage/ocs-operator pull request #2255
Opened 2023-11-05 04:15 UTC by aruniiird

2023-12-28 07:31 UTC, aruniiird commented
@umangachapagain , can you please merge this backport (for release-4.12) PR?
Thanks

2023-12-28 08:17 UTC, umangachapagain requested changes
Can you link the original PRs here?
These commits look different to me from the original.

2024-01-03 07:25 UTC, aruniiird commented
> Can you link the original PRs here? These commits look different to me from the original.

These are the same set of commits which was needed for the release-4.13 backport,
https://github.com/red-hat-storage/ocs-operator/pull/2254/commits

2024-01-03 07:33 UTC, umangachapagain approved these changes

2024-01-03 07:36 UTC, merged