Move API to separate go module
red-hat-storage/ocs-operator pull request #2304
Opened 2023-12-06 07:08 UTC by umangachapagain

This PR moves ocs-operator API package into it's own go module.
It also removes api package dependency on controller-runtime.

2023-12-14 09:21 UTC, iamniting requested changes
I think we should also add the make command similar to the `deps-update` and `verify-deps` or under these commands itself to update the go module inside API directory.

2023-12-14 10:03 UTC, umangachapagain commented
/cherry-pick release-4.15

2023-12-14 10:23 UTC, iamniting requested changes

2023-12-14 10:23 UTC, iamniting commented on Makefile
> +	@echo "Running deps-update on api submodule"
Can you also update the paths under `hack/verify-dependencies.sh`

2023-12-14 11:07 UTC, iamniting approved these changes

2023-12-14 11:09 UTC, merged

2023-12-15 05:09 UTC, leelavg commented
@umangachapagain / @iamniting will you be creating a followup PR to support repo for multi [modules](https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#go-workspaces-go-118)?

2023-12-15 05:32 UTC, umangachapagain commented
> @umangachapagain / @iamniting will you be creating a followup PR to support repo for multi [modules](https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#go-workspaces-go-118) lsp resolutions?
>
Done #2326