storageclassrequest: replace the filter logic with fieldIndexer
red-hat-storage/ocs-operator pull request #2456
Opened 2024-02-12 05:03 UTC by rewantsoni

Use fieldIndexer for efficient querying of owned svgs instead of using a custom filter function

2024-02-12 09:01 UTC, nb-ohad requested changes

2024-02-12 09:01 UTC, nb-ohad commented on main.go
> +			var owners []string
```suggestion
			owners := []string{}
```

2024-02-12 09:01 UTC, nb-ohad commented on main.go
> +		setupLog.Error(err, "unable to setup FieldIndexer")
```suggestion
		setupLog.Error(err, "unable to set up FieldIndexer for owner reference UIDs")
```

2024-02-13 06:38 UTC, leelavg reviewed
I couldn't unsee Ohad's review and I don't have new comments to add.

2024-02-15 14:25 UTC, nb-ohad requested changes

2024-02-15 14:25 UTC, nb-ohad commented on controllers/storageclassrequest/storageclassrequest_controller.go
> +const ownerUID = "ownerUID"
```suggestion
const ownerUID = "ownerUIDIndexName"
```

2024-02-16 08:36 UTC, rewantsoni commented on controllers/storageclassrequest/storageclassrequest_controller.go
> +const ownerUID = "ownerUID"
updated

2024-02-16 08:43 UTC, nb-ohad commented
/lgtm

2024-02-16 10:18 UTC, leelavg commented
/retest-required

2024-02-16 11:37 UTC, merged