Exports the cluster's name
red-hat-storage/ocs-operator pull request #2534
Opened 2024-03-28 10:31 UTC by raaizik

2024-03-28 10:56 UTC, raaizik commented
/cc @leelavg @nb-ohad

2024-03-28 16:14 UTC, nb-ohad requested changes

2024-03-28 16:14 UTC, nb-ohad commented on api/v1alpha1/storageconsumer_types.go
> +	ClusterName string `json:"clusterName"`
Can we move that up under cluster ID?

2024-03-31 08:36 UTC, nb-ohad commented on services/provider/interfaces/interfaces.go
> +	GetClusterName() string
```suggestion
	GetClusterID() string
	GetClusterName() string
	GetNamespacedName() string
```

2024-03-31 08:37 UTC, nb-ohad commented on services/provider/interfaces/interfaces.go
> +	SetClusterName(string) StorageClientStatus
```suggestion
	SetClusterID(string) StorageClientStatus
	SetClusterName(string) StorageClientStatus
	SetNamespacedName(string) StorageClientStatus
```

2024-04-01 05:51 UTC, rchikatw commented
changes look ok to me.

2024-04-01 06:39 UTC, leelavg approved these changes
please expand the PR summary and description, rest lg.

2024-04-01 08:58 UTC, nb-ohad commented
/lgtm

2024-04-01 09:01 UTC, merged