[MCG] Add support for deploying NooBaa operator SCC along with Rook SCCs
red-hat-storage/ocs-operator pull request #2655
Opened 2024-06-04 13:08 UTC by tangledbytes

This PR adds support for provisioning SCC for NooBaa operator alongside the Rook Operator. NooBaa operator added this SCC due to the IBM security requirements raised a few months ago.

2024-06-04 15:04 UTC, tangledbytes commented
Created this PR as part of IBM security fixes requirement for NooBaa/MCG.

/cc @malayparida2000 @iamniting

2024-06-05 04:12 UTC, iamniting requested changes
Pls, remove the extra signed-off line from the commit msg.

2024-06-05 04:12 UTC, iamniting commented on controllers/storagecluster/noobaa_system_reconciler.go
> +	nb.Spec.DBVolumeResources = convertCoreResourcesToVolumeResources(&dBVolumeResources)
```suggestion
	nb.Spec.DBVolumeResources = &corev1.VolumeResourceRequirements{
		Limits:   dBVolumeResources.Limits,
		Requests: dBVolumeResources.Requests,
	}
```

2024-06-05 07:31 UTC, iamniting approved these changes

2024-06-05 07:31 UTC, iamniting commented
/ok-to-test

2024-06-05 11:17 UTC, iamniting commented
/override Red Hat Konflux

2024-06-05 11:18 UTC, iamniting commented
/override "Red Hat Konflux"

2024-06-05 13:37 UTC, merged