Adding storage quota field to spec
red-hat-storage/ocs-operator pull request #2668
Opened 2024-06-18 06:42 UTC by rchikatw

- Adding spec field to storage consumer CR
- Will separate PR generated code & API code once its reviewed.
- Making it optional because for the consumer whos is having unlimited quota this field will not be set

2024-06-18 08:02 UTC, rchikatw commented
@leelavg @nb-ohad Please Review

2024-06-20 11:57 UTC, nb-ohad requested changes

2024-06-20 11:57 UTC, nb-ohad commented on api/v1alpha1/storageconsumer_types.go
> +	StorageQuotaInGi int `json:"storageQuotaInGi,omitempty"`
The term is GigaBytes (Gib)
```suggestion
	StorageQuotaInGiB int `json:"storageQuotaInGiB,omitempty"`
```

2024-06-20 15:22 UTC, nb-ohad commented
/lgtm

2024-06-20 15:53 UTC, merged