storagecluster: rewrite cephblockpool reconcilation
red-hat-storage/ocs-operator pull request #2670
Opened 2024-06-19 08:53 UTC by rewantsoni

The current implementation assumes only a single entity can touch the CR. Hence modifying the implementation such that the controller owns the specific fields and other entities are allowed to modify other fields of the cephblockpool CR.

Part of [RHSTOR-4886](https://issues.redhat.com/browse/RHSTOR-4886)

2024-07-08 08:12 UTC, rchikatw commented on controllers/storagecluster/cephblockpools.go
> +func (o *ocsCephBlockPools) addPeerSecretsToCephBlockPool(r *StorageClusterReconciler, storageCluster *ocsv1.StorageCluster, poolName string, poolNamespace string) cephv1.MirroringPeerSpec {
signature can also be modified to this I guess addPeerSecretsToCephBlockPool(r *StorageClusterReconciler, storageCluster *ocsv1.StorageCluster, `poolName, poolNamespace string`)

2024-08-16 09:44 UTC, iamniting requested changes

2024-08-16 09:44 UTC, iamniting commented on controllers/storagecluster/cephblockpools.go
> -				Name: ".mgr",
This name is missed from the new code.

2024-08-16 09:53 UTC, iamniting approved these changes
The PR looks good to me. Can you pls test it once?

/lgtm
/hold for testing

2024-08-16 09:59 UTC, iamniting approved these changes

2024-08-16 10:18 UTC, rewantsoni commented
Editing of the cephblockpool mirroring field manually is allowed even if mirroring is not enabled from storageCluster CR
```
[rewantsoni scripts] k get storagecluster ocs-storagecluster -oyaml | yq '.spec.mirroring'
{}

[rewantsoni scripts] k get cephblockpool ocs-storagecluster-cephblockpool -oyaml | yq '.spec.mirroring'
enabled: true
mode: image
```

2024-08-16 10:25 UTC, iamniting commented
/unhold

2024-08-16 11:28 UTC, merged

2024-08-21 06:24 UTC, rewantsoni commented
/cherry-pick release-4.17