Reducing the apps group resources privilege according to the required…
red-hat-storage/ocs-operator pull request #2716
Opened 2024-07-29 11:58 UTC by OdedViner

… verbs

2024-07-30 05:11 UTC, Nikhil-Ladha requested changes
Few questions/changes:
- Are all the permissions really needed?
- Please add a meaningful commit message to the commit.
- Split the generated changes to a separate commit.

2024-07-30 21:57 UTC, OdedViner commented
> Few questions/changes:
> 
> * Are all the permissions really needed? -> As you can see in the description of the PR, the testing process was serial and I checked the logs in ocs operator pod  
> * Please add a meaningful commit message to the commit. -> can you send me example
> * Split the generated changes to a separate commit. -> got it

2024-07-31 05:00 UTC, Nikhil-Ladha commented
Ex commit msg: https://github.com/red-hat-storage/ocs-operator/pull/2720/commits/338cf6910f8350fd8789baefadb09e8e286c2ce0

2024-08-20 04:53 UTC, Nikhil-Ladha commented
/retest

2024-08-20 04:54 UTC, Nikhil-Ladha commented
Please remove the bz number from the commit msg, let it be generic to the code.

2024-08-21 11:05 UTC, OdedViner commented
> Please remove the bz number from the commit msg, let it be generic to the code.

done

2024-08-21 12:23 UTC, Nikhil-Ladha commented
/retest

2024-08-21 15:19 UTC, Nikhil-Ladha approved these changes

2024-08-22 04:42 UTC, iamniting approved these changes

2024-08-22 04:44 UTC, merged