provider: add annotation to StorageCluster about deployment mode
red-hat-storage/ocs-operator pull request #2717
Opened 2024-07-29 14:49 UTC by leelavg

setting an annotation on the storagecluster allows to only look at metadata for finding the configured mode rather than parsing the spec.

this helps for client-operator to decide reconciliation.

2024-07-29 14:54 UTC, leelavg commented
/hold

for more testing

2024-07-29 17:58 UTC, nb-ohad requested changes

2024-07-29 17:58 UTC, nb-ohad commented on controllers/storagecluster/reconcile.go
> +		if instance.Spec.AllowRemoteStorageConsumers && util.AddAnnotation(instance, "mode", "provider") {
Please use a standardized annotation name `ocs.openshift.io/deployment_mode` or something similar

2024-07-30 12:40 UTC, nb-ohad commented
LGTM, but prefer the @iamniting will also take a look

2024-07-30 14:20 UTC, iamniting requested changes
Pls add in the commit msg why do we need this annotation?

Add a comment as well in the code.

2024-07-31 02:40 UTC, leelavg commented
/unhold

2024-07-31 04:14 UTC, leelavg commented
/cherry-pick release-4.16

2024-07-31 05:12 UTC, leelavg commented
Tested as mentioned in https://github.com/red-hat-storage/ocs-client-operator/pull/196#issuecomment-2259679385

2024-07-31 06:44 UTC, iamniting approved these changes

2024-07-31 06:47 UTC, merged

2024-08-13 04:20 UTC, leelavg commented
/cherry-pick release-4.17

2024-08-13 04:22 UTC, leelavg commented
disregard.