Refactor imports in odfinfoconfig.go
red-hat-storage/ocs-operator pull request #2729
Opened 2024-08-02 06:25 UTC by vbnrh

- Add 'gopkg.in/yaml.v2' import.
- go fmt import changes

This change is required because 'sigs.k8s.io/yaml' produced a PascalCase output, which the UI cannot use. By using the new dependency 'gopkg.in/yaml.v2', we ensure the output is in camelCase, which the UI can use for its unmarshalling.

2024-08-02 07:42 UTC, GowthamShanmugam commented
/retitle Bug 2302448: Refactor imports in odfinfoconfig.go

2024-08-02 07:48 UTC, GowthamShanmugam commented
**Note:
   Move the BZ to Modified once after this PR is merged: https://github.com/red-hat-storage/ocs-operator/pull/2686, Otherwise it leads to FailedQA.**

2024-08-02 07:50 UTC, GowthamShanmugam commented
I checked the configMaps keys, it is just like what UI is expecting. Thanks!

2024-08-02 10:43 UTC, vbnrh commented
/test ocs-operator-bundle-e2e-aws

2024-08-05 08:59 UTC, vbnrh commented
/test ocs-operator-bundle-e2e-aws

2024-08-05 09:11 UTC, umangachapagain requested changes

2024-08-05 09:11 UTC, umangachapagain commented on controllers/storagecluster/odfinfoconfig.go
> +
```suggestion
```

2024-08-05 09:16 UTC, umangachapagain commented on controllers/storagecluster/odfinfoconfig.go
> +
imports need to be well formatted.

2024-08-05 09:46 UTC, umangachapagain approved these changes

2024-08-05 12:07 UTC, vbnrh commented
/test ocs-operator-bundle-e2e-aws

2024-08-05 13:25 UTC, merged