rbdmirror: add a blockpool name label in the rados namespace cr
red-hat-storage/ocs-operator pull request #2883
Opened 2024-11-08 09:49 UTC by parth-gr

add a blockpool name in the lable so UI can watch for the rados namespace that belongs to the particular blockpool

2024-11-08 10:04 UTC, rewantsoni requested changes
I was wondering if ocs-operator is the right place to add this label and if adding the label from Rook would make more sense. If Rook adds the label then, irrespective of the controller that creates the CR, we will always have the label. As an example, for external mode we might also require monitoring and might have to add the label on the CR from where we are creating radosNS CR for external mode. WDYT?

2024-11-08 10:06 UTC, parth-gr commented
> I was wondering if ocs-operator is the right place to add this label and if adding the label from Rook would make more sense. If Rook adds the label then, irrespective of the controller that creates the CR, we will always have the label. As an example, for external mode we might also require monitoring and might have to add the label on the CR from ting radosnamespacce where we are creating radosNS CR for external mode. WDYT?

we are only doing mirroring in provider mode for the rados namespace, in future, we can change it to rook but for now, I think we can be specific

2024-11-08 10:07 UTC, rewantsoni commented on controllers/storagerequest/storagerequest_controller.go
> +	blockPoolNameLabel         = "blockPoolName"
If we are having this here, could we have something like `ocs.openshift.io/cephblockpool-name`

2024-11-08 10:11 UTC, rewantsoni commented
> we are only doing mirroring in provider mode for the rados namespace, in future, we can change it to rook but for now, I think we can be specific

If it is a small fix and we can have it from the rook, I suggest making changes to the rook so that we don't have to change it in the future.

2024-11-08 10:31 UTC, parth-gr commented
> > we are only doing mirroring in provider mode for the rados namespace, in future, we can change it to rook but for now, I think we can be specific
> 
> If it is a small fix and we can have it from the rook, I suggest making changes to the rook so that we don't have to change it in the future.

@travisn should we do at rook?
As this label would be unnecessary for other deployments, but it wont hurt

2024-11-11 06:31 UTC, rewantsoni commented
/lgtm

2024-11-11 07:05 UTC, malayparida2000 approved these changes
/lgtm

2024-11-11 07:11 UTC, malayparida2000 commented
/cc @iamniting

2024-11-11 08:01 UTC, iamniting approved these changes

2024-11-11 13:42 UTC, merged