Create ClusterRoleBinding to fetch in-cluster monitoring metrics
red-hat-storage/ocs-operator pull request #2892
Opened 2024-11-13 12:37 UTC by ezio-auditore

2024-11-14 05:58 UTC, umangachapagain commented on config/rbac/role.yaml
> +  - k8s
What is this resource? Why is it required?

2024-11-14 05:58 UTC, umangachapagain commented on controllers/ocsinitialization/ocsinitialization_controller.go
> +	r.Log.Info("K8s cluster role binding creation succeeded", "Name", crb.Name)
Needs to be more descriptive or can be dropped.

2024-11-20 07:33 UTC, leelavg reviewed
why should an operator create ClusterRoleBinding as that's the role of olm/admin?

2025-03-05 06:57 UTC, ezio-auditore commented on config/rbac/role.yaml
> +  - k8s
Dropped not required

2025-03-05 06:57 UTC, ezio-auditore commented on controllers/ocsinitialization/ocsinitialization_controller.go
> +	r.Log.Info("K8s cluster role binding creation succeeded", "Name", crb.Name)
dropped the comment

2025-03-05 08:54 UTC, ezio-auditore commented
> why should an operator create ClusterRoleBinding as that's the role of olm/admin?

@leelavg this is required only on ROSA HCP platforms and k8s service monitor needs this cluster rolebinding according to the namespace the user deploys it in.

2025-03-05 09:36 UTC, leelavg commented
> > why should an operator create ClusterRoleBinding as that's the role of olm/admin?
> 
> @leelavg this is required only on ROSA HCP platforms and k8s service monitor needs this cluster rolebinding according to the namespace the user deploys it in.
- there is a discrepancy here, isn't it? yaml says `openshift-storage` and code says whichever ns the operator is displayed which mostly is different in ROSA
- does ocs-op already have RBAC to create CRB?

doesn't olm already update the namespace in CRB if that's part of the bundle?

2025-03-05 10:14 UTC, ezio-auditore commented
> > > why should an operator create ClusterRoleBinding as that's the role of olm/admin?
> > 
> > 
> > @leelavg this is required only on ROSA HCP platforms and k8s service monitor needs this cluster rolebinding according to the namespace the user deploys it in.
> 
> * there is a discrepancy here, isn't it? yaml says `openshift-storage` and code says whichever ns the operator is displayed which mostly is different in ROSA
> * does ocs-op already have RBAC to create CRB?
> 
> doesn't olm already update the namespace in CRB if that's part of the bundle?

@leelavg 
I did check and yes OLM updates CRB if part of the bundle. It already does this for ocs-operator,ux-backend-server
I can just add a CRB for prometheus-k8s SA to have cluster-monitoring-view  . Any reconcile actions will not be required.

2025-03-06 05:17 UTC, umangachapagain requested changes

2025-03-06 05:17 UTC, umangachapagain commented on config/rbac/cluster_monitoring_view_prometheus_k8s_role_binding.yaml
> +kind: ClusterRoleBinding
This is not the right file to add custom RBACs. These will be removed when we update generated content.
Add this CRB to [ocs-operator/rbac](https://github.com/red-hat-storage/ocs-operator/tree/6d2b355ea4cc183d493379f88d4f8b5fde3721f2/rbac) directory.

Then run `make update-generated` and `make gen-latest-csv` to update the operator bundle.

2025-03-06 05:17 UTC, umangachapagain commented on config/rbac/cluster_monitoring_view_prometheus_k8s_role_binding.yaml
> +  namespace: openshift-storage
```suggestion
```
It can be dropped as we expect OLM to fill it based on namespace where operator gets deployed.

2025-03-06 07:47 UTC, ezio-auditore commented on config/rbac/cluster_monitoring_view_prometheus_k8s_role_binding.yaml
> +kind: ClusterRoleBinding
Done

2025-03-06 07:47 UTC, ezio-auditore commented on config/rbac/cluster_monitoring_view_prometheus_k8s_role_binding.yaml
> +  namespace: openshift-storage
Dropped

2025-03-06 11:17 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-03-07 09:21 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-03-13 04:51 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-03-20 10:00 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-03-24 11:40 UTC, parth-gr commented on deploy/ocs-operator/manifests/cluster_monitoring_view_prometheus_k8s_role_binding.yaml
> +  name: prometheus-k8s
need to specify the namespace?

2025-03-24 11:41 UTC, ezio-auditore commented on deploy/ocs-operator/manifests/cluster_monitoring_view_prometheus_k8s_role_binding.yaml
> +  name: prometheus-k8s
No olm handles that while installing

2025-05-20 10:48 UTC, umangachapagain approved these changes

2025-05-20 13:09 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-05-21 05:15 UTC, parth-gr approved these changes

2025-05-21 07:53 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-05-28 07:38 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-05-29 10:30 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-07-07 07:28 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-07-10 08:05 UTC, ezio-auditore commented
/test ocs-operator-bundle-e2e-aws

2025-08-11 06:49 UTC, malayparida2000 commented
/retest

2025-08-11 06:50 UTC, malayparida2000 commented
@ezio-auditore Can you please get the QE acks etc required for the Bugs so they can be backported

2025-10-07 07:11 UTC, leelavg approved these changes

2025-10-07 07:18 UTC, parth-gr commented on deploy/ocs-operator/manifests/cluster_monitoring_view_prometheus_k8s_role_binding.yaml
> +  namespace: openshift-storage
I think OLM will add this, right?
We can remove it

2025-10-07 07:18 UTC, parth-gr commented on templates/k8smetricsservicemonitor.go
> +				CAFile: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt",
If I remember this is default populated, do we need to provide it explicitly

2025-10-07 07:18 UTC, parth-gr commented on templates/k8smetricsservicemonitor.go
> +					ServerName:         ptr.To("prometheus-k8s.openshift-monitoring.svc"),
It wont be different in case of in house prometheus?

2025-10-07 07:25 UTC, ezio-auditore commented on deploy/ocs-operator/manifests/cluster_monitoring_view_prometheus_k8s_role_binding.yaml
> +  namespace: openshift-storage
Yes but a field named 'namespace' should be there along with a placeholder namespace name. Otherwise CI will fail. I had tried this before

2025-10-07 07:26 UTC, ezio-auditore commented on templates/k8smetricsservicemonitor.go
> +				CAFile: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt",
I am changing the InsecureSkipVerify field to false , that is the reason I am explicitly setting the values

2025-10-07 07:28 UTC, ezio-auditore commented on templates/k8smetricsservicemonitor.go
> +					ServerName:         ptr.To("prometheus-k8s.openshift-monitoring.svc"),
This is for the service monitor which federates metrics from the prometheus located in `openshift-monitoring`  , I don't think it will be any different

2025-10-07 07:35 UTC, parth-gr commented on templates/k8smetricsservicemonitor.go
> +					ServerName:         ptr.To("prometheus-k8s.openshift-monitoring.svc"),
It would be `(prometheus.%s.svc, namespace)` for the ROSA?

2025-10-07 07:35 UTC, parth-gr commented on templates/k8smetricsservicemonitor.go
> +					ServerName:         ptr.To("prometheus-k8s.openshift-monitoring.svc"),
It would be `(prometheus.%s.svc, namespace)` for the ROSA?

2025-10-07 07:36 UTC, parth-gr commented on templates/k8smetricsservicemonitor.go
> +					ServerName:         ptr.To("prometheus-k8s.openshift-monitoring.svc"),
In case of ROsa, `prometheus located in openshift-monitoring` wont fetch the metrics?

2025-10-07 07:41 UTC, ezio-auditore commented on templates/k8smetricsservicemonitor.go
> +					ServerName:         ptr.To("prometheus-k8s.openshift-monitoring.svc"),
This change is for odf-prometheus specifically for ROSA .Metrics provided by the in-cluster prometheus needs to be fetched into odf namespace for example (`kube_node_status_condition`).  This change is not meant for the in-cluster prom to fetch anything from odf namespace.

2025-10-07 08:10 UTC, parth-gr commented on templates/k8smetricsservicemonitor.go
> +					ServerName:         ptr.To("prometheus-k8s.openshift-monitoring.svc"),
Ack

2025-10-07 08:10 UTC, parth-gr commented
/lgtm

2025-10-07 09:42 UTC, merged

2025-11-25 07:16 UTC, ezio-auditore commented
/cherry-pick release-4.19

2025-12-11 17:46 UTC, DanielOsypenko commented on deploy/ocs-operator/manifests/cluster_monitoring_view_prometheus_k8s_role_binding.yaml
> +  namespace: openshift-storage
@ezio-auditore I don't see that bug https://issues.redhat.com/browse/DFBUGS-370 was fixed. 
We do not use `openshift-storage` ns in our testing, but use `odf-storage`. We have a restriction to use `openshift-` prefix on Rosa HCP. Can field be an issue, why we don't see the a fix?