external: fix reconcile for external mode
red-hat-storage/ocs-operator pull request #2904
Opened 2024-11-21 17:19 UTC by parth-gr

currently the reconcile stops before the
external resources are created if any failure occurs, Fix the reconcile to return success only when
all the resources are created successfully

2024-11-21 17:20 UTC, parth-gr commented
/assign @iamniting @travisn

2024-11-21 17:54 UTC, parth-gr commented
Testing:
Resources were created successfully
```
[rider@localhost rook]$ oc get cephBlockPoolRadosNamespace 
NAME         PHASE   BLOCKPOOL   AGE
namespace1   Ready   rbd         23s
[rider@localhost rook]$ oc get sc
NAME                                                   PROVISIONER                             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ocs-external-storagecluster-ceph-rbd                   openshift-storage.rbd.csi.ceph.com      Delete          Immediate              true                   2d10h
ocs-external-storagecluster-ceph-rbd-rados-namespace   openshift-storage.rbd.csi.ceph.com      Delete          Immediate              true                   25s
ocs-external-storagecluster-ceph-rgw                   openshift-storage.ceph.rook.io/bucket   Delete          Immediate              false                  2d10h
ocs-external-storagecluster-cephfs                     openshift-storage.cephfs.csi.ceph.com   Delete          Immediate              true                   2d4h
openshift-storage.noobaa.io                            openshift-storage.noobaa.io/obc         Delete          Immediate              false                  2d10h
thin-csi (default)                                     csi.vsphere.vmware.com                  Delete          WaitForFirstConsumer   true                   2d10h
[rider@localhost rook]$ 

```

2024-11-22 06:00 UTC, iamniting requested changes
Changes looks good to me, though we need to work on a commit msg.

`Defer secret hash update until all resources are successfully created`

`This update ensures that the secret hash in the storage cluster status is updated only after all resources are created successfully.`

`Previously, the status was updated prematurely, preventing the reconcile loop from re-running whether there was a failure or success. This change enables the reconcile process to continue retrying until all resources are successfully created.`

2024-11-22 06:03 UTC, malayparida2000 requested changes

2024-11-22 06:03 UTC, malayparida2000 commented on controllers/storagecluster/external_resources.go
> +	instance.Status.ExternalSecretHash = extSecretChecksum
Instead of changing the function signature to return the hash we should just call r.externalSecretDataChecksum(instance) here to get the hash.

2024-11-22 06:03 UTC, malayparida2000 commented on controllers/storagecluster/external_resources.go
> +func (r *StorageClusterReconciler) sameExternalSecretData(instance *ocsv1.StorageCluster) (string, bool) {
Let's not return the hash from this function, The function name suggests it should return a boolean so let it be that way.

2024-11-22 06:39 UTC, iamniting approved these changes

2024-11-22 06:39 UTC, iamniting commented on controllers/storagecluster/external_resources.go
> +	// at this point the checksums are different, so update it
```suggestion
	//At this point all the resources are created successfully, update the status
```

2024-11-22 07:52 UTC, malayparida2000 approved these changes
/lgtm

2024-11-22 08:48 UTC, merged